### ISSUE TITLE
About BetaLoss

### ISSUE THREAD

**Issue by joshua840** [zifanw/smoothed_geometry#1]
Thank you for uploading great code. and I have a question regarding BetaLoss. 

In line 22, I think B_T and B should be swapped.

What I understand is that we want to calculate W(diag(p)-p^Tp)W^T to approximate H, and then we find a maximum eigenvalue for the approximated H.

In smooth_space.py, variable 'A' looks diag(p)-p^Tp, and following e and U are eigenvalue and eigenvector of A, respectively. 

Since B = WUS, BB^T gives W(U S S^T U^T) W^T = W(US^2U^T) W^T = WAW^T = H. (Note S = Sigma in code)

However, in line 22, this code calculates B^TB, not BB^T

Could you tell me what I missing?

**Comment by zifanw** [comment]
Hi Joshua, 

The purpose is to ensure the matrix you do eigen-decompose up to the size of c by c where c is the number of classes. Note that, consider ,`B=WUS`, then `B^T B = S^TU^2S` while `BB^T = WU^2W^T`. While `BB^T` gives you H, `B^TB` gives you another matrix that has the same eigenvalues and we don't care about the eigenvectors actually. 

The following statement is what we refer to in the Appendix C of https://arxiv.org/pdf/1902.00407.pdf
<img width="633" alt="Screen Shot 2021-03-18 at 10 46 04" src="https://user-images.githubusercontent.com/15389771/111645528-2990b580-87d7-11eb-9bde-2eeec560e74d.png">

Hope this may help you.

**Comment by joshua840** [comment]
I'm very grateful to you for your help, Zifan.
